### ISSUE TITLE
<Part-A> Close functionality is not working for Sign-In form

### ISSUE THREAD

**Issue by Gangadhard2** [sarthak2019/FrontEndOfABloggingWebsite#3]
![Sign-in](https://user-images.githubusercontent.com/29808674/60150452-abcc8100-978d-11e9-88b5-6c633b90a14b.PNG)

1.CLick on Sign-in in index page
2.Click on close icon "x"

Actual: closing is not working
Expected: CLosing functionality should work

**Comment by sarthak2019** [comment]
The issue was fixed and the code was merged(commit id: a71727cc67113d11e01c6af87555e53adec30de0).
