### ISSUE TITLE
<Part-A> The buttons "All Posts" and "Create Post" are not placed at the horizontal & vertical centre of the screen.

### ISSUE THREAD

**Issue by sarthak2019** [sarthak2019/FrontEndOfABloggingWebsite#5]
![image](https://user-images.githubusercontent.com/47344929/60201038-04228200-9865-11e9-8ae3-b17cee2f8fd7.png)

**Comment by Gangadhard2** [comment]
yes, work on this bug

**Comment by codewarrior-X** [comment]
I think this is as per user monitor screen

![index html - Google Chrome 2019-06-27 11 09 47](https://user-images.githubusercontent.com/47395107/60239716-37e4c280-98cc-11e9-922c-a23b98d036bb.jpg)

**Comment by Gangadhard2** [comment]
Fixed it!

**Comment by sarthak2019** [comment]
The issue was resolved in the commit id: cb30e9c96497c85cde8976c1d212f207970f785d.
