### ISSUE TITLE
<Part-A> The code related to header class are present in index.css and index.js files. They should be present inside header.css an header.js files

### ISSUE THREAD

**Issue by sarthak2019** [sarthak2019/FrontEndOfABloggingWebsite#6]

**Comment by Gangadhard2** [comment]
Raghavendra, pls take car eof this bug!

**Comment by codewarrior-X** [comment]
This is done

**Comment by codewarrior-X** [comment]
2.You must refer to the "index.css" file inside the "css" folder and define all your css inside that file (for the "index.html" file)

3. You must refer to the "index.js" file inside the "js" folder and define all your Javascript inside that file (for the "index.html" file)

Thats why i did there..

**Comment by sarthak2019** [comment]
Part A: Creating the Homepage

Relevant files to work on: index.html, index.js, header.js, index.css, header.css

Part B: Creating list of blogs;

In this section, we would be creating a page called "bloglist.html" which would display the list of all blog posts.

Relevant files to work on: bloglist.html, bloglist.css, bloglist.js
So the person working on part A has to work on header.js and header.css  files and he needs to place the codes for header class inside header.css and header.js files. In Part B we need to refer to the header.js and header.css files. But we don't have the option to refer to the index.js and index.css files from part b HTML file, i.e., bloglist.html.

So you need to move all the required codes for header class into header.js and header.css files.

**Comment by sarthak2019** [comment]
The issue was resolved in the commit id: f382460f53ecf0c5ad54293cb8faa4a98b5443e7.
